# Generated by Django 4.1.1 on 2022-12-08 10:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("airsoft_shops", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="members",
            field=models.ManyToManyField(
                related_name="shop_member",
                through="airsoft_shops.Member",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="logo",
            field=models.ImageField(
                blank=True, default="nopic.jpeg", upload_to="shop_logo"
            ),
        ),
    ]
