# Generated by Django 4.1.1 on 2022-11-29 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("airsoft_organization", "0001_initial"),
        ("airsoft_event", "0001_initial"),
        ("airsoft_polygon", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="event_owner",
                to="airsoft_organization.organization",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="polygon",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="airsoft_polygon.polygon",
            ),
        ),
    ]
