# Generated by Django 4.1.1 on 2022-11-30 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("airsoft_polygon", "0002_polygon_city"),
        ("airsoft_event", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="polygon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="airsoft_polygon.polygon",
            ),
        ),
    ]
