# Generated by Django 4.1.1 on 2022-12-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airsoft_event", "0003_scenario_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="banner",
            field=models.ImageField(
                blank=True, default="nopic.jpeg", upload_to="event_banner"
            ),
        ),
    ]
