# Generated by Django 4.1.1 on 2023-02-02 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("airsoft_event", "__first__"),
        ("airsoft_registration", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teamregistration",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registered_teams",
                to="airsoft_event.event",
            ),
        ),
    ]
