# Generated by Django 4.1.1 on 2022-11-29 13:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BasicGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_private", models.BooleanField(default=False)),
                ("is_open", models.BooleanField(default=True)),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True, related_name="member", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "request_user",
                    models.ManyToManyField(
                        blank=True,
                        related_name="request_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
