# Generated by Django 4.1.1 on 2022-11-27 15:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("airsoft_membership", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="basicgroup",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
