# Generated by Django 4.1.1 on 2022-11-24 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("airsoft_membership", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "user_group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="org_owner",
                        serialize=False,
                        to="airsoft_membership.basicgroup",
                    ),
                ),
                ("Description", models.TextField()),
                ("logo", models.ImageField(blank=True, upload_to="org_logo")),
            ],
        ),
    ]
