# Generated by Django 4.1.1 on 2022-11-29 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("airsoft_organization", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="organization",
            old_name="Description",
            new_name="description",
        ),
    ]
