# Generated by Django 4.1.1 on 2022-12-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airsoft_organization", "0003_alter_organization_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="logo",
            field=models.ImageField(
                blank=True, default="nopic.jpeg", upload_to="org_logo"
            ),
        ),
    ]
