# Generated by Django 4.1.1 on 2022-09-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_name", models.CharField(max_length=64)),
                ("event_address", models.CharField(max_length=64)),
                ("organizer", models.CharField(max_length=64)),
                ("duration", models.DurationField(verbose_name="duration")),
                ("body", models.TextField(blank=True, null=True)),
                ("additional_block1", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
