# Generated by Django 4.1.1 on 2022-11-21 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("teams", "0001_initial"),
        ("org", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdditionalServices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service", models.TextField()),
                ("price", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("place", models.CharField(max_length=64)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("body", models.TextField(blank=True, null=True)),
                ("additional_block1", models.TextField(blank=True, null=True)),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="URL"),
                ),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owner",
                        to="org.organizations",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventReg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "additionalservice",
                    models.ManyToManyField(blank=True, to="event.additionalservices"),
                ),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_reg",
                        to="event.event",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventTags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name="Sides",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("side", models.CharField(max_length=64)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post",
                        to="event.eventreg",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RegisteredTeams",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("addservice", models.ManyToManyField(to="event.additionalservices")),
                (
                    "players",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="player",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="event.eventreg",
                    ),
                ),
                (
                    "side",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="event.sides"
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registered_team",
                        to="teams.teams",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="eventreg",
            name="sides",
            field=models.ManyToManyField(
                blank=True, related_name="sides", to="event.sides"
            ),
        ),
        migrations.AddField(
            model_name="eventreg",
            name="teams",
            field=models.ManyToManyField(
                blank=True, related_name="regd_teams", to="event.registeredteams"
            ),
        ),
        migrations.CreateModel(
            name="EventPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("body", models.TextField(blank=True, null=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post",
                        to="event.event",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="Tags", to="event.eventtags"
            ),
        ),
    ]
