# Generated by Django 4.1.1 on 2022-09-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0002_remove_event_organizer_eventpost"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventTags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="tags",
            field=models.ManyToManyField(related_name="event", to="event.eventtags"),
        ),
    ]
