# Generated by Django 4.1.1 on 2022-11-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0003_alter_registeredteams_registration_send"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registeredteams",
            name="registration_send",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
