# Generated by Django 4.1.1 on 2022-10-01 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0003_eventtags_event_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="tags",
            field=models.ManyToManyField(related_name="Tags", to="event.eventtags"),
        ),
        migrations.AlterField(
            model_name="eventpost",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post",
                to="event.event",
            ),
        ),
    ]
