# Generated by Django 4.1.1 on 2022-10-01 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0004_alter_event_tags_alter_eventpost_event"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="event_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="event_address",
            new_name="place",
        ),
    ]
