# Generated by Django 4.1.1 on 2022-11-21 11:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("event", "0004_alter_registeredteams_registration_send"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registeredteams",
            name="players",
        ),
        migrations.AddField(
            model_name="registeredteams",
            name="mby",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="mby", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="registeredteams",
            name="no",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="no", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="registeredteams",
            name="yes",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="yes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
