# Generated by Django 4.1.1 on 2022-11-22 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("org", "0001_initial"),
        ("event", "0005_remove_registeredteams_players_registeredteams_mby_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="owner",
                to="org.organizations",
            ),
        ),
        migrations.AlterField(
            model_name="registeredteams",
            name="addservice",
            field=models.ManyToManyField(blank=True, to="event.additionalservices"),
        ),
        migrations.AlterField(
            model_name="registeredteams",
            name="registration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registered",
                to="event.eventreg",
            ),
        ),
    ]
