# Generated by Django 4.1.1 on 2022-11-21 06:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teams",
            name="members",
            field=models.ManyToManyField(
                blank=True, related_name="member", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
