# Generated by Django 4.1.1 on 2022-11-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airsoft_polygon", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="polygon",
            name="city",
            field=models.CharField(max_length=124, null=True),
        ),
    ]
