# Generated by Django 4.1.1 on 2023-01-28 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("airsoft_gear", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Members",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "friend"),
                            (2, "member"),
                            (3, "manager"),
                            (4, "owner"),
                        ],
                        default=1,
                    ),
                ),
                ("main", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("city", models.CharField(max_length=64)),
                ("description", models.TextField()),
                (
                    "chevron",
                    models.ImageField(
                        blank=True, default="nopic.jpeg", upload_to="chevron/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(auto_now=True)),
                ("is_private", models.BooleanField(default=False)),
                (
                    "members",
                    models.ManyToManyField(
                        related_name="memb",
                        through="airsoft_teams.Members",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pattern",
                    models.ManyToManyField(
                        blank=True, default="nopic.jpeg", to="airsoft_gear.pattern"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeamRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_request",
                        to="airsoft_teams.team",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="members",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_members",
                to="airsoft_teams.team",
            ),
        ),
        migrations.AddField(
            model_name="members",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
