# Generated by Django 4.1.1 on 2022-11-25 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("airsoft_membership", "0001_initial"),
        ("airsoft_gear", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "user_group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="team_owner",
                        serialize=False,
                        to="airsoft_membership.basicgroup",
                    ),
                ),
                ("description", models.TextField()),
                ("chevron", models.ImageField(blank=True, upload_to="chevron")),
                (
                    "pattern",
                    models.ManyToManyField(blank=True, to="airsoft_gear.pattern"),
                ),
            ],
        ),
    ]
