# Generated by Django 4.1.1 on 2022-12-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airsoft_gear", "0001_initial"),
        ("airsoft_teams", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="chevron",
            field=models.ImageField(
                blank=True, default="nopic.jpeg", upload_to="chevron/"
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="pattern",
            field=models.ManyToManyField(
                blank=True, default="nopic.jpeg", to="airsoft_gear.pattern"
            ),
        ),
    ]
