# Generated by Django 4.1.1 on 2022-12-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airsoft_teams", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="members",
            name="role",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "friend"), (2, "member"), (3, "manager"), (4, "owner")],
                default=1,
            ),
        ),
    ]
