# Generated by Django 4.1.1 on 2022-12-08 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("airsoft_teams", "0002_alter_team_chevron_alter_team_pattern"),
    ]

    operations = [
        migrations.AlterField(
            model_name="members",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
