# Generated by Django 4.1.1 on 2023-02-12 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("airsoft_teams", "0002_alter_team_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="team",
            options={
                "permissions": (
                    ("g_view_team", "View_team_guardian"),
                    ("g_create_team_post", "View_team_guardian"),
                )
            },
        ),
    ]
