# Generated by Django 4.1.1 on 2023-02-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airsoft_teams", "0003_alter_team_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team_short",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="team",
            options={
                "permissions": (
                    ("g_view_team", "View_team_guardian"),
                    ("g_create_team_post", "Creat_post_guardian"),
                    ("g_team_member_manager", "Mamber_manager_guardian"),
                    ("g_team_vote", "Team_vote_guardian"),
                )
            },
        ),
    ]
