# Generated by Django 4.1.1 on 2023-02-26 13:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("airsoft_teams", "0004_team_short_alter_team_options"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Team_Member",
            new_name="TeamMember",
        ),
        migrations.DeleteModel(
            name="Team_short",
        ),
        migrations.DeleteModel(
            name="TeamPostComment",
        ),
    ]
