# Generated by Django 4.1.1 on 2022-12-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airsoft_teams", "0005_members_main"),
    ]

    operations = [
        migrations.AlterField(
            model_name="members",
            name="main",
            field=models.BooleanField(default=False),
        ),
    ]
