name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py') --load-plugins pylint_django --load-plugins pylint_django.checkers.migrations --disable=missing-docstring --disable=missing-class-docstring --disable=missing-function-docstring --disable=undefined-loop-variable --disable=duplicate-code --disable=inconsistent-return-statements --disable=unused-import --disable=unused-import --disable=undefined-loop-variable --disable=invalid-name  --disable=import-outside-toplevel --disable=django-not-configured