# Generated by Django 4.1.1 on 2023-02-12 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("airsoft_teams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color", models.CharField(max_length=32, null=True)),
                ("number", models.CharField(max_length=32, null=True)),
                ("car_brand", models.CharField(max_length=32, null=True)),
                ("model", models.CharField(max_length=32, null=True)),
                ("combat_car", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(default="no_avatar.png", upload_to="avatars"),
                ),
                ("city", models.CharField(max_length=32, null=True)),
                ("country", models.CharField(max_length=32, null=True)),
                ("gear", models.CharField(max_length=32, null=True)),
                ("weapons", models.CharField(max_length=32, null=True)),
                ("car", models.CharField(max_length=32, null=True)),
                ("bbs", models.CharField(max_length=32, null=True)),
                ("birthday", models.DateField(null=True)),
                ("is_privet", models.BooleanField(default=False)),
                (
                    "friend_list",
                    models.ManyToManyField(
                        related_name="friend", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_profile",
                        to="airsoft_teams.team",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
