# Generated by Django 4.1.1 on 2022-12-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("u_auth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(default="no_avatar.png", upload_to="avatars"),
        ),
    ]
