# Generated by Django 4.1.1 on 2022-12-10 12:20

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("u_auth", "0002_userprofile_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="bbs",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="birthday",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="car",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="city",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="country",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="friend_list",
            field=models.ManyToManyField(
                null=True, related_name="friend", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="gear",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_privet",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="weapons",
            field=models.CharField(max_length=32, null=True),
        ),
    ]
