# Generated by Django 4.1.1 on 2022-12-10 12:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "u_auth",
            "0003_userprofile_bbs_userprofile_birthday_userprofile_car_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="birthday",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="friend_list",
            field=models.ManyToManyField(
                related_name="friend", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
