# Generated by Django 4.1.1 on 2023-01-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("u_auth", "0004_alter_userprofile_birthday_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color", models.CharField(max_length=32, null=True)),
                ("number", models.CharField(max_length=32, null=True)),
                ("car_brand", models.CharField(max_length=32, null=True)),
                ("model", models.CharField(max_length=32, null=True)),
                ("combat_car", models.BooleanField(default=False)),
            ],
        ),
    ]
